### ISSUE TITLE
add to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [lpanebr/yazi-plugins#2]
Hi cool plugin!
Would you like to add it to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? It would be a very nice addition to it?
Just follow the PR template and you should be good with it.

Thanks!

**Comment by lpanebr** [comment]
Thanks. [PR](https://github.com/AnirudhG07/awesome-yazi/pull/27) created!

**Comment by AnirudhG07** [comment]
Hi, just dropping by, I saw you have a new plugin. would be nice to have it in awesome-yazi! 
Thanks!
